name: wordpress-adminpage
services:
  phpcli:
    type: php:8.2
    via: cli
    xdebug: true
    composer_version: 2-latest
tooling:
  php:
    service: phpcli
  composer:
    service: phpcli
  phpcs:
    service: phpcli
    command: vendor/bin/phpcs
  phpcbf:
    service: phpcli
    command: vendor/bin/phpcbf
  rector:
    service: phpcli
    command: vendor/bin/rector
